using System;
using System.Collections;
using System.Diagnostics;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Xml;
using MyData.domain;
using MyData.utils;


namespace MyData.repos
{
    public abstract class AbstractRepository<E> : CRUDRepository<E>
    {
        protected int LastId;
        private ArrayList entities = new ArrayList();
        private Validator<E> validator;

        private String storageFile;

        private Logger logger;

        protected AbstractRepository()
        {
            LastId = 0;

//            logger = new Logger();

            //define the XML filename
            storageFile = Constants.ResourceFilesPath;
            storageFile = storageFile + GetNameForGenericE() + "Storage.xml";
        }

        public void SetXMLFilename(String filename)
        {
            //change the current XML filename
//            storageFile = Constants.ResourceFilesPath;
            storageFile = filename;
        }

        public void SetValidator(Validator<E> validator)
        {
            this.validator = validator;
        }

        public abstract void SetEntityId(E e);

        public void Save(E e)
        {
            validator.Validate(e);

            LastId++;
            SetEntityId(e);

            entities.Add(e);
        }

        public ArrayList GetAll()
        {
            return entities;
        }

//      XML IO

        public void SaveAllToXML()
        {
            //prepare the settings used for the XML file
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;

            //create the writer to write into the file
            XmlWriter writer = XmlWriter.Create(storageFile, settings);
            //append the start tag to the document
            writer.WriteStartDocument();

            //disclaimer
            writer.WriteComment("This file is generated by the program.");

            //get the properties of the object
            var properties = GetTypeForGenericE().GetProperties();

            writer.WriteStartElement("objects");
            foreach (var entity in entities)
            {

                //add the object tag
                writer.WriteStartElement(GetNameForGenericE());

                foreach (var property in properties)
                {
                    //get the field name and value
                    var fieldName = property.Name;
                    var fieldValue = property.GetValue(entity).ToString();

                    writer.WriteElementString(fieldName, fieldValue);
                }

                //end object tag
                writer.WriteEndElement();

            }

            //end the parent element
            writer.WriteEndElement();

            writer.Flush();
            writer.Close();

//            logger.LogWarning("All saved","SaveAllToXML");
        }

        public void LoadAllFromXML()
        {
            //instantiate a reader
            XmlReader reader = XmlReader.Create(storageFile);

            E element = (E) Activator.CreateInstance(GetTypeForGenericE());
            PropertyInfo property;

            //get generic class and type
            String className = GetNameForGenericE();
            Type classType = GetTypeForGenericE();

            //while the reader can read
            while (reader.Read())
            {

                //depending on the node type, we switch to other things
                //a switch is nice here if we decide to deal with more
                //than Element and EndElement
                switch (reader.NodeType)
                {
                    //in case we find an element
                    case XmlNodeType.Element:

                        String readerName = reader.Name;

                        //create a new element to be added to
                        //when it passes an object node with
                        //the class name
                        if (readerName == className)
                        {
                            element = (E) Activator.CreateInstance(classType);
                        }
                        else
                        {
                            //get the property read from the element via reflection
                            property = classType.GetProperty(readerName);

                            //if the property is valid
                            //get the value, convert it to proper type
                            //and store it into the element
                            if (property != null)
                            {

                                String rawValue= reader.ReadString();

                                object value = Convert.ChangeType(rawValue, property.PropertyType);

                                if (property.CanWrite) property.SetValue(element, value);
                            }
                        }

                        break;

                    case XmlNodeType.EndElement:
                        //if we finished reading the element
                        //we add it to the repo

                        if (reader.Name == className)
                        {
                            entities.Add(element);
                        }
                        
                        break;

                } //end switch 
                      
            } //end reader while

            reader.Close();

//            logger.LogWarning("All loaded", "LoadAllFromXML");
        }

        //      reflection methods

        private Type GetTypeForGenericE()
        {
            return typeof (E);
        }

        private String GetNameForGenericE()
        {
            return GetTypeForGenericE().Name.ToLower();
        }
        
    }
}